// <auto-generated />
namespace CadastroAnuncio.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class CadastroAnuncioMigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CadastroAnuncioMigration));
        
        string IMigrationMetadata.Id
        {
            get { return "202105151120384_CadastroAnuncioMigration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
